### PR TITLE
Monophobia modularity [ready to merge]

### PR DESCRIPTION
**Pull request by OverDriveZ**
## About The Pull Request
Moves a variable inside mobs to define in an easier way what mob is a pet and what isn't.
Amazingly cats are now pets

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: tweakes monophobia
/:cl:

### CODE REVIEW

**Review by Tk420634 — APPROVED** [review]
cats are dinner, what are you talking about

**Comment by OverDriveZ** [comment]
> cats are dinner, what are you talking about

You're a cat, what are YOU talking about

**Comment by Tk420634** [comment]
my ass is on the menu BOYS

**Comment by Tk420634** [comment]
Untitled

**Comment by OverDriveZ** [comment]
> Untitled

lmao what the fuck

**Pull request merged**
