### PR TITLE
Gun keybinds: toggle safety, scope and firemode [ready to merge]

### PR DESCRIPTION
**Pull request by OverDriveZ**
## About The Pull Request
Coming back (I'm a stubborn motherfucker), now with a selection of gun keybinds. Makes it possible to select a keybind to toggle safety, scope and firemode.

immagine

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
tweak: tweakes how firearms work.
/:cl:

### CODE REVIEW

**Comment by Tk420634** [comment]
I think this is the one bay-esque change from the list that I'm actually concerned about, i'll had to do a proper announcement about it so I won't quite merge juuuuuuuuuuuuust yet as its ass AM.  But here in a few hours, probably.

**Review by Tk420634 — APPROVED** [review]

**Comment by EtheoBoxxman** [comment]
The bay feature that does this was an optional preference toggle, not a forced feature.
I think this would be better off like that, as well.

**Comment by OverDriveZ** [comment]
yeah, I was following a list of things they asked me to do. apparently this one was the exception, it's fine if it doesn't get merged

**Comment by Tk420634** [comment]
> The bay feature that does this was an optional preference toggle, not a forced feature. I think this would be better off like that, as well.

Don't worry too much about it, we're pretty sure we can actually skip this one off the list, what we really need is a safety hotkey.

**Comment by Tk420634** [comment]
This man is insane.

**Pull request merged**
