### PR TITLE
Some new tails, and ears

### PR DESCRIPTION
**Pull request by thingpony**
All I had energy for
Adds three new tails, a new ear, and tow horns

### CODE REVIEW

**Comment by Tk420634** [comment]
Jon, can you check this when you have time?

**Comment by GremlingSS** [comment]
file ./modular_coyote/code/mam_ears_coyote.dm is missing a trailing newline

**Comment by GremlingSS** [comment]
Just put a new line at the end of the file c:

**Review by Tk420634 — APPROVED** [review]
:+1:

**Pull request merged**
