### PR TITLE
Snowflake loadout stuff + Hell Nomad radio fix (100% real no fake)

### PR DESCRIPTION
**Pull request by RinPin**
## About The Pull Request

Adds a cosmetic variant of the 10mm SMG obtainable through a blueprint, and a cosmetic variant of the brass knuckles to my loadout, also fixes the hell nomad radio by changing the order the channels were in, which somehow makes it work as intended.
## Pre-Merge Checklist
- [Y ] You tested this on a local server.
- [ Y] This code did not runtime during testing.
- [ Y] You documented all of your changes.

### CODE REVIEW

**Comment by RinPin** [comment]
augh, DMI stuff

**Comment by RinPin** [comment]
I can't get it to recognize the new, untouched projectile.DMI, please whoever merges this, just ignore that change, it's 5 AM and it refuses to understand that nothing has changed in it.

**Comment by RinPin** [comment]
thank you jesus, it works

**Review by Tk420634 — APPROVED** [review]
lmao, lol even

**Pull request merged**
