### PR TITLE
resolve CI runtimes

### PR DESCRIPTION
**Pull request by CASEYGUNGEON**
## About The Pull Request

Three CI runtimes:
- 2 incorrectly defined drink recipes
- Language Holders initializing on mobs during a unit test as they were being QDEL'd
- a large number of conflicting tea recipes were fixed by adding a unit of sugar to the required reagents of the less-complicated recipe.

This'll probably make CI useful on PRs.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by CASEYGUNGEON** [comment]
im watching the CI run rn. gimme a sec to double check the language holders thing

**Comment by Tk420634** [comment]
Integration checks a bitch, just hit it with a million rocks

**Comment by CASEYGUNGEON** [comment]
read em and weep

firefox_4UstPK2Lyu

**Comment by Tk420634** [comment]
Ready to merge? :0

**Comment by CASEYGUNGEON** [comment]
> Ready to merge? :0

good now 👍

**Review by TalkingCactus — APPROVED** [review]

**Pull request merged**
