### PR TITLE
Pillz Here!

### PR DESCRIPTION
**Pull request by FarmWizard**
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added pill bottles for lewdchem
add: Added an aphrodisiac foam grenade
add: A new lewd pillz vendor
/:cl:

### CODE REVIEW

**Comment by FuzzyFuzlet** [comment]
I’m not certain if aphrodisiac grenades are a good idea. on the one hand, everyone has a toggle to turn aphrodisiacs off to prevent prefbreak, but on the other hand, the temptation to toss these into public areas will be great

**Review by Superlagg — APPROVED** [review]

**Review by Tk420634 — CHANGES_REQUESTED** [review]
Mostly good, but I've spoken with Fuzz & Dan and we're all not down for the Party grenade.  Cull it and this should be fine.

**Comment by FuzzyFuzlet** [comment]
I suggest putting a smoke machine in a corner of heaven’s night and in a dorm or two if you want smokey funsies tho others might disagree. the grenades have too high of a risk of gassing unconsenting targets

**Comment by FarmWizard** [comment]
removed the chemnade and the object from the vending machine

**Review by Superlagg — APPROVED** [review]

**Review by Superlagg — APPROVED** [review]

**Review by Tk420634 — APPROVED** [review]

**Pull request merged**
