### PR TITLE
Science Circuit Printer

### PR DESCRIPTION
**Pull request by Dangerlurking**
## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Adds a circuit printer to science
del: Removes a pile of tech trash where the circuit printer now is.
:cl:

### CODE REVIEW

**Comment by PrettyPsychoForAWolf** [comment]
Keep in mind, ages back (months ago, like 8 or so) it was said that the circuit imprinter should be yeeted and thus all of them were from the server. However, that was then. Things might be different now.

I'll ping Fenny to see his thoughts.

**Comment by Dangerlurking** [comment]
> Keep in mind, ages back (months ago, like 8 or so) it was said that the circuit imprinter should be yeeted and thus all of them were from the server. However, that was then. Things might be different now.
> 
> I'll ping Fenny to see his thoughts.

The issue is; mechs still require boards which are impossible to find out in the wild, and if any machines like the autolathe get smashed, we are shit outta luck and have to pray that an admeme will help out.

**Comment by Tk420634** [comment]
> > Keep in mind, ages back (months ago, like 8 or so) it was said that the circuit imprinter should be yeeted and thus all of them were from the server. However, that was then. Things might be different now.
> > I'll ping Fenny to see his thoughts.
> 
> The issue is; mechs still require boards which are impossible to find out in the wild, and if any machines like the autolathe get smashed, stolen, or otherwise made unavailable, we are shit outta luck and have to pray that an admeme will help out.

Gimme some time to ponder the orbs, the servers changed a LOT since we last decided not to include it, and we had a reason I just. I've slept a lot since then lmao

**Review by Tk420634 — APPROVED** [review]
Fuck it we ball.

**Pull request merged**
