### PR TITLE
Den and Nash Upper 2 Facelift

### PR DESCRIPTION
**Pull request by Dumbdumn5**
## About The Pull Request
Completely and utterly changes every part of the Den, adds 2 new ruins and a bunch of mineable rock to the uppermost Nash z-level, with barrier walls between dungeons obviously left intact.

New Den Z-2: 
image

New Den Z-3: 
image

New Ruin 1, Raider Cabin:
image

New Ruin 2, Machine Shop:
image

Post Machine-Shop Reward, isolated mountain house, figured a livable area instead of a ton of loot might be cool as a prize:
image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Two new ruins, mineable rock added to upper Tex-Arkana.
del: Removed Old Den
tweak: Entirely New Den
balance: rebalanced something
/:cl:

### CODE REVIEW

**Review by Tk420634 — CHANGES_REQUESTED** [review]
[ ] - Put a buncha pastries back in the donut shop, homies need their calories.
[ ]- Put some validball spawner points in your ruins, those are the dark green X's, and can also spawn uncommon loot or artifacts (and hopefully anomalies eventually)
[ ] - Let me shave Moira, please 🙏

**Comment by Dumbdumn5** [comment]
Calories: 
image

Validball Spawners: 
image
image

Stand-in for Moira (Given I don't play her as much anymore), this is Buddy, my stunt double:
image

**Comment by Dumbdumn5** [comment]
@Tk420634 
image

**Review by Tk420634 — APPROVED** [review]

**Comment by Tk420634** [comment]
Bud'll have to work.

**Pull request merged**
