### PR TITLE
Rynn's snowflake loadout & adds hotwiring aer9s to technofreak

### PR DESCRIPTION
**Pull request by RadiantFlash7**
## About The Pull Request

Just a dumb custom loadout I made.
Supplies rynn with:
1  holotag
1 armored labcoat (same stats as an armor kit)
1 scribe accessory pin
1 blueprint for a modified aer9 with a custom sprite/description (Note: This blueprint requires an AER9, advanced bench and several parts)
image
image
image

--------------------
Loadout aside, I also added the hotwired AER9 recipe to technofreak.
Using a blueprint that requires an AER9, several weapon parts and an advanced bench seemed like a decent way of going about this? If anything needs changing, let me know.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Recipe for Hotwired AER9
add: Recipe for custom Hotwired AER9
Add: custom armored labcoat for loadout
add: loadout for radiantflash
tweak: gave technofreak the ability to craft hotwired aer9s.
imageadd: added icons for custom aer9 in backslot, gunhands, and energy.dmi
imageadd: added icons for armored labcoat
/:cl:

### CODE REVIEW

**Comment by FuzzyFuzlet** [comment]
this overall looks solid, just a couple issues more on our end than yours. we recently completed a complete refactoring of weapon stats and so it will be a simple fix for me to bring your new gun into the proper format, but it will have to wait until tomorrow, when the refactor is fully in.
additionally...It's a complicated problem, but seems the hotwired aer9 was missed when we removed armor piercing from pretty much all energy weapons. to put it simply, armor piercing is very difficult to balance at all, and always just makes a given gun feel weak against anything that isn't a heavily armored player or specific few boss mobs. I need to overhaul the hotwired aer9, take its AP away, but give it a meaty damage increase, and likely magazine increase as well, but it will all have to wait till tomorrow

**Comment by Tk420634** [comment]
Right, so as an example. Because I want to add to what Fuzz is saying.  This is a weapon with 34 damage, that requires an advance workbench to make that does not kill geckos reliably in one shot with only 5 shots.  That is actively worse, in almost every way than a large variety of our starting guns.  

Fuzz also mentioned to me that Plasma has this same issue.  Armor Pen works, and is obviously quite good, but there are breakpoint minimums that should be met to help drive the weapon into 'usable' territory and not 'insanely niche weapon that only gets used to fight the renegade miester'.  

With AP, when you don't hit the breakpoints for mob health, you start going 'well, it needs more damage then', but how do you argue for more damage when you have a weapon that saws player armor in half.

Obviously, you didn't do anything wrong, but we'll gnaw on this tomorrow and get it sorted out, I can't believe that silly hotwired gun somehow got left behind, as gob said in dms earlier to me 'it's asscheeks.'

**Comment by RadiantFlash7** [comment]
> this overall looks solid, just a couple issues more on our end than yours. we recently completed a complete refactoring of weapon stats and so it will be a simple fix for me to bring your new gun into the proper format, but it will have to wait until tomorrow, when the refactor is fully in.
> additionally...It's a complicated problem, but seems the hotwired aer9 was missed when we removed armor piercing from pretty much all energy weapons. to put it simply, armor piercing is very difficult to balance at all, and always just makes a given gun feel weak against anything that isn't a heavily armored player or specific few boss mobs. I need to overhaul the hotwired aer9, take its AP away, but give it a meaty damage increase, and likely magazine increase as well, but it will all have to wait till tomorrow

Oh, Thats not a problem!
I just liked the idea of a modified aer9. I hadn’t really looked /too/ close at the stats, but I figured it might be a little niche from its sow fire rate and few shots. Either way- however you end up changing the stats for it works for me!

Is there anything that needs changing to my PR specifically, or is it stuff that you’ll be adjusting in the back end?

**Comment by RadiantFlash7** [comment]
> Right, so as an example. Because I want to add to what Fuzz is saying. This is a weapon with 34 damage, that requires an advance workbench to make that does not kill geckos reliably in one shot with only 5 shots. That is actively worse, in almost every way than a large variety of our starting guns.
> 
> Fuzz also mentioned to me that Plasma has this same issue. Armor Pen works, and is obviously quite good, but there are breakpoint minimums that should be met to help drive the weapon into 'usable' territory and not 'insanely niche weapon that only gets used to fight the renegade miester'.
> 
> With AP, when you don't hit the breakpoints for mob health, you start going 'well, it needs more damage then', but how do you argue for more damage when you have a weapon that saws player armor in half.
> 
> Obviously, you didn't do anything wrong, but we'll gnaw on this tomorrow and get it sorted out, I can't believe that silly hotwired gun somehow got left behind, as gob said in dms earlier to me 'it's asscheeks.'

I uh, actually never bothered to look at how much health mobs had. >_>;
But yeah, whatever damage/stats you guys want for it is fine, really! Either let me know what to adjust, or go with; or what needs to be done on my end!

**Comment by RadiantFlash7** [comment]
PR is out of date with master, and Fuzzy was gracious enough to make a new one with my stuff in it. <3

**Pull request closed without merging**
