### PR TITLE
Texarkana General Generators

### PR DESCRIPTION
**Pull request by ZeroNetAlpha**
Adds some solar panels to the roof of Texarkana General as well as adds a morgue to the hospital for Followers Use. Brings Texarkana General off of Fiat Power and actually makes the APC required to keep the building powered for long periods of time.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Adds a smoke break area to the hospital.
add: Adds a solar panel to the rooftop of the hospital.
add: Adds a vertibird landing spot to the rooftop of the hospital.
add: Adds a morgue to the second floor of the hospital.
add: Adds a basement level to the hospital.
tweak: Changed the location of the janitor's closet on the second floor of the hospital.
tweak: Makes the bathroom on the second floor of the hospital actually usable.
/:cl:

### CODE REVIEW

**Comment by ZeroNetAlpha** [comment]
So I'm not 100% sure why mapdiffbot keeps failing. It's whining about my id for the ladder going from floor 2 to the rooftop. It does at least work in game though, both up and down.

**Comment by ZeroNetAlpha** [comment]
it was quotemarks...

**Comment by ZeroNetAlpha** [comment]
Ok i'm not editing this anymore, i think I'm done.

**Comment by Tk420634** [comment]
I'll throw up a local test tomorrow and double check, map stuff can be stinky sometimes. <3

**Review by Tk420634 — APPROVED** [review]
<3

**Pull request merged**
