### PR TITLE
more customization for anthro insects

### PR DESCRIPTION
**Pull request by LiteralMushroom**
## About The Pull Request
I want to make a spider but I am being held back by the lack of customization for anthro insects.
Therefore: This PR.

(adds spider legs and mantis arms to the insect wings list. also ports a sprite and repurposes it as a new selectable sprite for anthro insects.)
Capture

## Pre-Merge Checklist
- [✓] You tested this on a local server.
- [✓] This code did not runtime during testing.
- [✓] You documented all of your changes.

## Changelog
:cl:
add: spider legs and mantis arms available for anthro insects
add: ported spider sprite for anthro insects
/:cl:

### CODE REVIEW

**Comment by LiteralMushroom** [comment]
wha tthefuck why are legs so complicated here???

**Comment by LiteralMushroom** [comment]
the legs are still fucking invisible how???

**Comment by LiteralMushroom** [comment]
agony

**Comment by LiteralMushroom** [comment]
> Reference

wait I literally forgot to rebuild it

**Comment by LiteralMushroom** [comment]
good news the legs exist now!!!!!!

**Review by Superlagg — APPROVED** [review]

**Comment by Tk420634** [comment]
don't bug me with this

**Pull request merged**
