### PR TITLE
Serbian Language Implementation

### PR DESCRIPTION
**Pull request by Dangerlurking**
## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Adds the Serbian language with the 2000s Yugoslav as its logo.
:cl:

### CODE REVIEW

**Comment by Dangerlurking** [comment]
Not sure why some of the checks are failing.

**Comment by OverDriveZ** [comment]
immagine

The reason it has linters errors is because there are some indentations that have been done using the space bar instead of the tab button

**Comment by Dangerlurking** [comment]
> immagine
> 
> The reason it has linters errors is because there are some indentations that have been done using the space bar instead of the tab button

I swear to god I did in fact use tab when indenting. Gonna try to fix it.

**Comment by Dangerlurking** [comment]
Okay the code is fuck ugly now, but if it works it works.

**Comment by OverDriveZ** [comment]
I 100% believe you! Sometimes it can happen for multiple reasons, copy-pasting from discord is the first one that comes to my mind as example

**Review by OverDriveZ — APPROVED** [review]
And approved

**Pull request merged**
