### PR TITLE
Merek is a bitch ass motherfucker he purred on my fucking wife

### PR DESCRIPTION
**Pull request by McRex007**
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Tk420634** [comment]
aww, babies first pr <3

**Comment by McRex007** [comment]
How do I ban maintainers from the upstream

**Comment by Tk420634** [comment]
> How do I ban maintainers from the upstream

maintpurge

**Comment by McRex007** [comment]
I commited it without pushing and I am stuck in hell now

**Comment by McRex007** [comment]
Still need a way to actually get it, anyone know how to add it to the civilian weapon kit?

**Comment by KathrinBailey** [comment]
> Still need a way to actually get it, anyone know how to add it to the civilian weapon kit?

Find the civilian weapon kit in code, easiest way is to find the typepath. Look in VSC for the weapon kit's name and you'll find it. Look at the other entries in the kit, adding yours to it should be very simple.

**Comment by McRex007** [comment]
Done and done! Its ready now, assuming there are no issues.

**Review by Tk420634 — APPROVED** [review]

**Pull request merged**
