### PR TITLE
Clinic Rework, Sewer T-Junction Fix, Texarkana chem-room addition

### PR DESCRIPTION
**Pull request by Dumbdumn5**
## About The Pull Request
I was told to make map changes if I didn't like the way the clinic looked, so, taking feedback from good-idea zone, I did.

This changes the first, second, and third floor of the clinic, adds in a proper space for the sewer stairs that got overlooked on the last map merge that removed the corner clinic, and adds another chem setup to the small hospital on the corner of Texarkana square to account for the one wasters lost from the map change.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Clinic, sewer stairs hole, chem room and second story to texarakna hospital
del: Removed old clinic, some tables
fix: fixed sewer stairs being blocked
/:cl:

New Clinic floors: 
image
image
image

New Sewer Entry:
image

New Upper Floor for Tex-Arkana mini-hospital:
image

### CODE REVIEW

**Comment by Dumbdumn5** [comment]
Also of note, first PR, I have no idea who to expect or if the horrifically large diff size is normal for maps or not.

**Comment by Dumbdumn5** [comment]
I think I realize why there may be so many differences- the map was out of date given a merge a few minutes ago, DNM while I fix that real quick.

**Comment by Dumbdumn5** [comment]
Right- updated those by snagging my changes and putting them onto the properly updated map from #2449

**Comment by Dumbdumn5** [comment]
RIGHT, horrors of the warp aside, I actually found out why there were such massive diffs and SOMEHOW I managed to copy-paste something hard enough it deleted Pahrump entirely there for a second, THANK YOU diff numbers for throwing me off and making me panic enough to properly fix it.

**Comment by jinxynii** [comment]
I dig it. I'll let this go over my own.

**Review by jinxynii — APPROVED** [review]

**Review by Tk420634 — APPROVED** [review]

**Pull request merged**
