### PR TITLE
Making smart holstering and trying to keybind a reload button [do NOT merge]

### PR DESCRIPTION
**Pull request by OverDriveZ**
## About The Pull Request
This does a lot of things.
To begin with, this is supposed to unholster your main weapon using a keybind, prioritising between the following slots in this order:
-Armor slot,
-Belt slot,
-Holster.

If the same keybind is being pushed again, and there's a weapon in your hands, then the system will return to your free hand the speedloader (magazine or clip, whatever it's needed) with the highest amount of ammo. (Maybe making it smart to fetch the right kind of ammo the gun needs?

Here's a simple example of what I did:

https://github.com/ARF-SS13/coyote-bayou/assets/64517916/6ff70e10-20d5-49f7-a9a7-60dff1a23301

## To-Do Checklist
- [ ] Making it fetch a weapon with a priority.
- [x] Making it fetch the fullest ammo clip.
- [ ] Making it fetch the matching kind of ammo for the gun you have in your other hand.

## Changelog
:cl:
add: Adds smart holstering.
/:cl:

### CODE REVIEW

**Comment by Tk420634** [comment]
smolstering

**Comment by OverDriveZ** [comment]
Iteration II does this now:

https://github.com/ARF-SS13/coyote-bayou/assets/64517916/11158bc8-52d9-4769-9f1d-8538b025abfc

**Comment by OverDriveZ** [comment]
Now it lets you akimbo

https://github.com/ARF-SS13/coyote-bayou/assets/64517916/1e10773f-7afd-40d0-9192-7876eb5fbf9b

**Comment by OverDriveZ** [comment]
professionist made a better version of this

**Pull request closed without merging**
