### PR TITLE
Permanent Tattoos

### PR DESCRIPTION
**Pull request by CASEYGUNGEON**
## About The Pull Request

When scars are saved at round end, all connected players that have tattoos marked as permanent will have them saved to their character. When that character respawns, they'll have those tattoos applied to them. The tattoos can be removed using the Tattoo Remover, a new item that shows up everywhere tattoo guns do.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added permanent tattoos and a tattoo remover.
/:cl:

### CODE REVIEW

**Comment by CASEYGUNGEON** [comment]
almost feature complete...

**Comment by Tk420634** [comment]
@Superlagg Hey dan, when you got time give this a sniff over and whack it with stick?

**Comment by Tk420634** [comment]
@CASEYGUNGEON Idk who you are but you just got my massive attention!

fenmelt

Thank you for all the hard work!  We'll have dan give it a sniffy since they made the original system and get it in asap!

**Comment by CASEYGUNGEON** [comment]
i should probably run `savecharacter` after removing a tattoo so you dont have to hang out all round afterward for it to actually be gone. id change it but im on my way to work right now

**Comment by Tk420634** [comment]
> i should probably run `save_character` after removing a tattoo so you dont have to hang out all round afterward for it to actually be gone. id change it right now but im on my way to work

no rush homie, I'll probably snatch you in a dm later tho.   xp

**Comment by CASEYGUNGEON** [comment]
> > i should probably run `save_character` after removing a tattoo so you dont have to hang out all round afterward for it to actually be gone. id change it right now but im on my way to work
> 
> 
> 
> no rush homie, I'll probably snatch you in a dm later tho.   xp  

yea for sure! not the same UN on discord though lol thats gonna be SWORDDOGGIRL

**Review by Superlagg — APPROVED** [review]

**Comment by Superlagg** [comment]
This is a very well made PR, you clearly know what you're doing! Thanks for expanding on this feature, been meaning to do it but never got around to it. =3

**Comment by CASEYGUNGEON** [comment]
> This is a very well made PR, you clearly know what you're doing! Thanks for expanding on this feature, been meaning to do it but never got around to it. =3

Thanks! I saw that it was intended and I wanted to use it myself so I figured I might as well take a crack at it.

I think tomorrow I'm just going to add that extra `save_character` i mentioned earlier and maybe just shove the tattoo removal into the tattoo gun itself to avoid clutter. and so i dont have to make a new sprite lol

after that i should be done messing with it

**Pull request merged**
