### PR TITLE
Virology in science

### PR DESCRIPTION
**Pull request by Dangerlurking**
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog
:cl:
add: Implements a virology wing into science, complete with chem machines, a pre-filled virology fridge, virus food vendor, vaccine machine, and monkey test subjects.
del: Removed a few trash piles, vines, and common loot generation spots where virology is now present.
:cl:

### CODE REVIEW

**Comment by Dangerlurking** [comment]
Forgot to add lights to the new area, dammit.

**Comment by Dangerlurking** [comment]
Should be ready to go now.

**Comment by Tk420634** [comment]
We already gave it a go and it was an abject failure of a department.  It just doesn't work with our gameplay flow.  Sorry love.

**Comment by Dangerlurking** [comment]
Pain.

**Pull request closed without merging**
