### PR TITLE
Ports three new versions of spider legs from Citadel.

### PR DESCRIPTION
**Pull request by LiteralMushroom**
## About The Pull Request
Adds the special spider legs the arachnid race on Citadel gets, as wings available to anthro insects AND everyone else.

Also I made them grayscale because grayscale good.

somewhat jank but spider legs cool. maybe I will dejankify them at a later date, but it's like 2 am at the time of typing this and I need to go to Sleep

## Pre-Merge Checklist
- [✓] You tested this on a local server.
- [✓] This code did not runtime during testing.
- [✓] You documented all of your changes.

## Changelog
:cl:
add: some more spider leg variants
/:cl:

Capture
Capture2
Capture3

### CODE REVIEW

**Comment by LiteralMushroom** [comment]
wait what the fuck??? we literally have them in the code completely unused

**Comment by LiteralMushroom** [comment]
yay testing time

**Comment by LiteralMushroom** [comment]
wait fuck I forgot to actually give pictures of what they look like before marking this as ready for review
uuuuuhhhhhhh

**Review by Tk420634 — APPROVED** [review]
Denied due to too many bugs

**Pull request merged**
