### PR TITLE
Fixes heavy-duty sheath and twin sheath; adds knife bandolier

### PR DESCRIPTION
**Pull request by BladeburstNINJA**
## About The Pull Request

Allows heavy-duty sheath to actually fit and take the items listed in fitting_swords. Adjusts the volume of the twin sheath so that it can fit its respective swords. Both items now fit on the belt slot. New knife bandolier that fits on neck and can hold knifebelt_allowed items.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
fix: fixes heavy-duty sheath and twin sheath
add: adds knife bandolier
/:cl:

### CODE REVIEW

**Comment by BladeburstNINJA** [comment]
Also fixes the sabre and rapier sheaths technically, though neither is player craftable anyways.

**Review by Tk420634 — APPROVED** [review]

**Comment by bearrrrrrrr** [comment]
uhhh issue here is that you can wear those things as accessories. dunno about this one in particular. i kinda get it but eeeeeeeeeh?

**Comment by WrongEnd** [comment]
Arguably this PR is just a bugfix restoring intended functionality. Whether or not it's balanced is for a different PR.

**Comment by bearrrrrrrr** [comment]
> Arguably this PR is just a bugfix restoring intended functionality. Whether or not it's balanced is for a different PR.

Unsure if this is a bugfix, since this was rebalanced in the large storage PR someone else did a few months ago.

**Comment by WrongEnd** [comment]
> Unsure if this is a bugfix, since this was rebalanced in the large storage PR someone else did a few months ago.

The sheath was intended to take every item in the provided list, and it did not. This is unintuitive. This PR restores it to using the list instead of half the entries being useless because of an undocumented secondary characteristic.

If it's to be balanced, it should be using the documented intended method, not through obscured obj weight class fuckery.

**Comment by BladeburstNINJA** [comment]
In response to feedback, the new commit makes the item slot of the heavy-duty sheath and the daisho belt now. Also adds a new knife bandolier that still fits in the neck slot and uses the previous storage_belt_holster stuff.

**Pull request merged**
