### PR TITLE
Trader crate addition, second attempt

### PR DESCRIPTION
**Pull request by DiscordWizard**
## About The Pull Request

Adds a very expensive crate (three times the rare crate one) that gives either a single uncommon unique or rare unique weapon once bought. Honestly I low-balled it to see what people would think, I'd prefer it have both the uncommon unique and the rare unique inside because at 15k point price there's absolutely no way to make any sort of benefit as a trader.

Also removes the chance to get an uncommon weapon in your rare crates. It's already 5k points for 3 weapons that together can sell for about half of that, we don't need even more of a chance to have our points wasted with a gun we can get with the cheaper boxes.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added two new unique weapon crates to the merchant selection
del: Deleted uncommon rolls from the rare crates
/:cl:

### CODE REVIEW

**Comment by DiscordWizard** [comment]
Revival of that one old pr I forgot to update for the sixth time, #3610

**Comment by Tk420634** [comment]
homeslice got them errors 🕺

**Comment by DiscordWizard** [comment]
Oh for
One moment I am too dumb to do this shit so late on the day, let me fix it

**Comment by DiscordWizard** [comment]
I thought we were moving the staves from the energy weapon list, atleast months ago, what changed? Do we keep them there?

**Comment by Kelprunner** [comment]
> I thought we were moving the staves from the energy weapon list, atleast months ago, what changed? Do we keep them there?

So, you'd have to talk to Kegdus about that. I don't have an actual reason for you, but I _think_ they were re-clumped with energy weapons because their damage types line up with them and that made it easier to sort out using the DPS calcs. While I'd, personally, prefer them to be with the cowboy spawner for thematic's sake I'm also sure they have a good reason for it. Or, at least, a decent one.

Also, as an aside, please make your new spawner 50/50 and not 30/30? It's... Something we need to go in and do later (if it maths out correctly) is make all the spawn chances add up to 100% so it's not utter hell trying to parse things or have to whip out a calculator to know what the various odds are.

**Comment by DiscordWizard** [comment]
Wasn't aware of that 50/50 thing, will try to update it

**Review by Tk420634 — APPROVED** [review]

**Pull request merged**
