### PR TITLE
Update Localization Files

### PR DESCRIPTION
**Pull request by Tk420634**
This PR will require multiple passes, mostly to remove needless Space Station 13 garbage we don't need to inherit.  All of them should be named Dorime so that we can quickly reference them when Dan has time for CBMERP.  In the meantime we can use this to test concepts and work out ideas.  Including the combo system, autoplapper, and our HUD

At the time of the first commit I have 62 errors and 115 problems.

They're knot terrible either, mostly that they have a different item slot system as ourselves (which should be able to be shifted over to ours without too much trouble.)

Along with a bunch of missing defines I can't be bothered to grab at this exact moment of posting from their code.

Oh, and duplicate definitions of has_whatevergenitals.

All in all not that far from a test run.

Preliminary Functionality
- [x] It compiles
- [x] You can open the window
- [x] You can self diddle 
- [x] Climaxing
- [x] You can other person diddle
- [ haha our runtime check is broken ] it doesn't runtime like a bastard (fuck you splurt)
- [x] remove the extreme stuff & 
- [x] safeguard the ones that do damage
- [x] Removal of extreme and cursed verbs

## Coyote Hard Requirements
- [x] *MERP consent plapper (PLAP, people laying atop people tool).  No MERP can happen without this.
- [x] PLAP REQ: Yes/No/No Call Admin(r-u-sure) --- Whitelist User omitted for CBMERP
- [x] Creation of Coyote Prototype Self-Verb
- [x] Creation of Coyote Prototype Partner-Verb
- [x] replace all splurt noises with placeholder blush.oggs 
- [x] erp verbs default to on 
- [x] make the system check for only four genitals, benis, bagina, booba and tail OR allow players to build a favorites tab and have NO checking 
- [x] overhaul interaction screen, with toggle for autoclimax 
- [x] Remove the beaker icon, because we aren't going to be using liquids for a while
- [x] MERP REQ: Autoplapper: 3 options 🔧 @Superlagg 
- [x] Merping Self, automatically tested by @Tk420634 
- [x] rightclick option to interact
- [x]  Autoclimaxer (rolling/manual), technically works but automatically triggers at any%, not 100%+.   🔧 @Superlagg 
- [x] verb spam cooldown 🔧 @TalkingCactus did this, but we broke it. So. @Superlagg 
- [x] Make sure new verbs print to chat correctly (old ones do already) @Tk420634 testing, @Superlagg fixing
- [x] moan spam cooldown 🔧 @TalkingCactus did this to, but we broke it lol.  So. @Superlagg 
- [x] Double check self actions

Coyote Soft Requirements
- [x] If Client Pref is turned off you see **NO** *merp information from anyone.  Normal Scene rules will absolutely still apply
- [x] Six and a half trillion new Coyote Verbs 🔧 @Tk420634    
- [x] Add more color to the verbs with {}

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by Superlagg** [comment]
Doe ream

**Comment by Tk420634** [comment]
Gonna replace all the splurt oggs today and probably make two dozen more verbs

**Comment by Tk420634** [comment]
Updated mission goals with who is doing what, so we can keep it clean

**Comment by Tk420634** [comment]
Once more into the breach, lads.
Hang_in_there

**Comment by Tk420634** [comment]
We need to figure out what these barricades are doing.

This is otherwise ready.

**Comment by Tk420634** [comment]
@Superlagg @TalkingCactus

**Review by Superlagg — APPROVED** [review]

**Pull request merged**
